spring.application.name=stock-analyzer

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

admin.username=${ADMIN_USERNAME}
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}

fmp.api-key=${FMP_API_KEY}
fmp.base-url=https://financialmodelingprep.com/stable

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=3600000

stock.refresh.market-days-cron=0 00 07 * * *
stock.refresh.stock-data-cron=0 30 07 * * *
stock.refresh.zone=Europe/Prague
stock.refresh.stock-data-limit=100